name: Build Google Custom Image Using Packer

on:
  push:
    branches:
      - packer-br

jobs:
  build_ami:
    name: integration_test_packer_build
    runs-on: ubuntu-latest

    steps:
      - name: Check if this push is from a PR merge
        run: |
          if [[ ${{ github.event_name }} == 'push' && ${{ contains(github.event.head_commit.message, 'Merge pull request') }} ]]; then
            echo "This push is from a pull request merge."
          else
            echo "This push is not from a pull request merge."
            exit 1
          fi

      - name: Checkout code
        if: success()
        uses: actions/checkout@v2

      #ADD INTEGRATION FROM JOBS
      - name: Zip Folder
        if: success()
        run: zip -r webapp.zip .

      - name: Setting up packer
        uses: hashicorp/setup-packer@main

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}'
        
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
  
      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      - name: Run Packer
        run: |
          cd packer
          packer init test.pkr.hcl
          packer build test.pkr.hcl
