name: pull-request-raise-actions

on:

  # push:
  #   branches:
  #     - main

  
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout 🛎️
        uses: actions/checkout@v3
      -
        name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      -
        name: Install pipenv
        run: |
          pip install -r ./app/requirements.txt
          pip install pytest-cov
      -
        name: Run tests
        run: |
          coverage run -m pytest -v .
          coverage report -m
          

